CREATE DATABASE IF NOT EXISTS SPOTIFY_DATABASE;
USE SPOTIFY_DATABASE;

CREATE TABLE IF NOT EXISTS MUSICAS (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    ARTISTA VARCHAR(100) NOT NULL,
    ALBUM VARCHAR(100) NOT NULL,
    URI VARCHAR(255) NOT NULL,
    DURACAO INT NOT NULL,
    PRIMARY KEY (ID)
);

DELETE FROM MUSICAS WHERE ID = 1;

SELECT * FROM MUSICAS;

SELECT * FROM MUSICAS WHERE NOME LIKE '%Aquele%';


INSERT INTO MUSICAS (NOME, ARTISTA, ALBUM, URI, DURACAO) VALUES 
('Aquele Abraco', 'Chico Buarque', 'Chico Buarque', 'spotify:track:3Qm86XLflmIXVm1wcwkgDK', 200);

UPDATE MUSICAS SET 
NOME = 'Aquele Abraço', ARTISTA = 'Chico Buarque', ALBUM = 'Chico Buarque', URI = 'spotify:track:3Qm86XLflmIXVm1wcwkgDK', DURACAO = 200 
WHERE ID = 1;